# Generated by Django 3.2.7 on 2021-09-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('github_url', models.URLField()),
                ('host_url', models.URLField()),
                ('prev_image', models.URLField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
