# Generated by Django 3.2.7 on 2021-09-08 10:11

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('github_url', models.URLField()),
                ('host_url', models.URLField()),
                ('prev_image', models.URLField()),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=api.models.lang_default, max_length=10), size=None)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
