# Generated by Django 3.2.7 on 2021-09-14 13:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('github_url', models.URLField()),
                ('host_url', models.URLField(blank=True, null=True)),
                ('prev_image', models.CharField(max_length=500, null=True)),
                ('display_image', models.CharField(max_length=500, null=True)),
                ('languages', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('short_description', models.CharField(max_length=100, null=True)),
                ('long_description', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
    ]
