# Generated by Django 3.2.7 on 2021-09-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.JSONField(null=True),
        ),
    ]
