# Generated by Django 3.2.7 on 2021-09-08 12:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
