# Generated by Django 3.2.7 on 2021-09-08 13:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
