# Generated by Django 3.2.7 on 2021-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='display_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='prev_image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
