# Generated by Django 3.2.7 on 2021-09-11 16:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210910_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
