# Generated by Django 3.2.7 on 2021-09-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='host_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
